version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    versioning-strategy: increase
    target-branch: 'main'
    allow:
      - dependency-type: 'development'
      - dependency-type: 'production'
